name: student_listing
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.1
  dio: ^5.3.3
  flutter_mobx: ^2.1.0+1
  mobx_codegen: ^2.4.0
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  brasil_fields: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0
  build_runner: ^2.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/
